In [1]:
m = [1, 2, 4]
n = [3, 4, 5]

In [3]:
print(m + n)

[1, 2, 4, 3, 4, 5]


In [5]:
import numpy as np

In [7]:
m = np.array([1, 2, 3])
n = np.array([3, 4, 5])

In [9]:
m+n

array([4, 6, 8])

In [11]:
type(np)

module

In [13]:
type(m)

numpy.ndarray

In [17]:
squ = m + n
np.square(squ)

array([16, 36, 64])

In [19]:
sub = m - n
sub

array([-2, -2, -2])

In [21]:
mul = m*n
mul

array([ 3,  8, 15])

In [23]:
m-1

array([0, 1, 2])

In [25]:
m*2

array([2, 4, 6])

In [29]:
np.dot(m, n)

26

In [37]:
a = np.array([1, 2, 3, 4, 5])
b = [6, 7, 8, 9, 10]
b = np.array(b)
type(b)

numpy.ndarray

In [39]:
a.ndim

1

In [41]:
b.shape

(5,)